### PR TITLE
document usage

### PR DESCRIPTION
**Pull request by edouard-lopez**
I'm starting by describing how end-user will work with the project. Then develop it

### CODE REVIEW

**Comment by Pixelik** [comment]
That is a good approach. In that case, let's be more specific about the steps they'll have to take:

> Edit your `.layoutrc` 

Where will that file be located?

> Add `layoutlint.js` to your page

Aren't they supposed to `build` that file before using it (so that it include the above rules in some JS structure) ?

They also need to add a layoutlint.css to their page (it will style the popups), unless you want the above Js file to also inject that CSS so that the user only has to worry about one single file (layoutlint.js)

Can we change `.layoutrc` into something more meaningful like `layoutlint.config` ?

1. user edits `layoutlint.config`
2. user builds `layoutlint.js`
3. user adds `layoutlint.js` to the page (as well as the css file if the js file doesn't inject it for us)

**Comment by edouard-lopez** [comment]
✔️  I specified the location of `.layoutrc`.

## Config file

I like your suggestion to have a more explicit filename. However, some argument go against it :S

### Convention

`.layoutrc` follows the same convention as other linters (`eslint`→`.eslintrc`, `jshint`→`.jshintrc`, `jscs`→`.jscsrc`): 
* prefix with a `.` to hide the file on UNIX system ;
* [suffix with `rc`](https://stackoverflow.com/a/11030607/802365) designate [_run command_](https://www.wikiwand.com/en/Run_commands).

### Tooling
What bothers me with `.*rc` or `.conf` is it's generic extension so neither syntax highlighting nor formatter will work:

selection_164

Did you notice the typo on the left?

ℹ️ Pycharm/Webstorm let you set how to interpret `.*rc` not `*.conf`.

### Proposal

`eslint` also support `.eslintrc.js` as config file which is better IMHO cause you get syntax highlighting for free. So What do you think about: 

1. `.layoutrc`
1. `.layoutrc.js`
1. `.layout.conf.js`
1. `.layoutlintrc`
1. `.layoutlintrc.js`
1. `.layoutlint.conf.js`

ℹ️ I found the long form _layoutlint_ difficult to read.

**Comment by edouard-lopez** [comment]
To include the linter as described above we need to build it prior to inclusion in order to bundle the engine, the style and the config together. This was a 2000s-style approach, a more modern one will be to import everything as JS module with `rollup`, `webpack` or whatever:

    import layoutlinter from layoutlinter
    import layoutlinterConfig from './.layoutrc' 

This way we can disable it in production based on `NODE.ENV` value. Making it usable as a standalone can come later.

**Comment by Pixelik** [comment]
The SO post notes that `rc` can mean lots of things, neither of which is what this file is about. But I don't mind sticking with it if this will help devs understand what the file is about (even if its because a bad/false habit).

If the `rc` part eliminates the need for the `lint` part (when it comes to understanding what the file is about) we can leave `lint` out.

So `.layoutrc` or `.layoutrc.js` (whichever will also allow for some syntax highlighting).

I wasn't suggesting _how_ the file will be included necessarily but more as to which steps the dev needs to follow to end up with layout-linting on a page. As long as we document every step in this PR (whatever that may be) we'll know what/how to develop the plugin.

**Comment by Pixelik** [comment]
outdated

**Pull request closed without merging**
