### PR TITLE
v0.0.0

### PR DESCRIPTION
**Pull request by Pixelik**
- adds example-app  showing how layout-linter will be used
- allows for source passed to layout-linter to be an HTML document or the HTML itself
- example rules created
- script parsing through example rules and creating relevant notifications created

TODO:
- create example "bad" HTML source input
- write tests
- modularise code

### CODE REVIEW

**Comment by Pixelik** [comment]
Could you please review the syntax the of [.layoutrc](https://github.com/peopledoc/layout-linter/blob/example-structure/example-app/.layoutrc) and tell me what you think of it? 

This is the file where the layout-linter user will be adding their rules. I hope what each rule does is pretty self-explanatory but I would like your input as to the syntax/structure I went for, whether they're over-engineered, too many of them or whether everything looks fine 🙂 

I don't want to move forward too much without having sorted this syntax out first.

ping @peopledoc/tribe-js

**Comment by njoyard** [comment]
Looks nice overall, very readable as @saintsebastian said.

I guess the and/or thing will mean `and1 AND and2 AND ... AND (or1 OR or2 OR ...)`, right? It would be nice to document, or maybe even rename the `and` and `or` keys to something like `allOf` and `anyOf`?

Are the `is` and `isNot` necessary ? Couldn't we just do that with the selector?

**Comment by xcambar** [comment]
@Pixelik thanks, putting that in a separate file is already very nice!

I agree with @njoyard about the redundancy of `is`, `isNot` and `selector`, but, [**food for thoughts**]:
* putting everything under `selector` can make huuuuge selectors. That argument is in favor of using only `is/isNot`
* `is` is not as explicit nor common terminology as `selector`. This argument is in favor of `selector`
* Is there a requirement/check/guarantee that these properties are limited to the root element? Would that be an error to write: `selector: ".parent .child"`? I'd suggest it is, but then, the naming should make it explicit.

* I'm not sure I understand how `and`/`or` works, how they can be coposed etc... not a big fan as is.
* How about renaming:
  * `direct` to `children`
  * `indirect` to `descendants`
* How about merging `is` and `has` within a single `with` property? `with.direct`, `with.attr`.  `is/isNot/has/hasNot` would become `with/without`.

Lastly, I'd suggest to allow to split the configuration into multiple files, for  real life examples would require **a lot** of rules (think Bootstrap, for instance...)

Despite the number of comments (you know me...), this is definitely a lot of work in the right direction! Thanks and congrats for putting all of that together!

**Comment by Pixelik** [comment]
Thank you everyone for the helpful input!
<br>
I need to clarify one thing about the structure:
```
{
  'selector': '{some CSS selector}',
  .......
  ...
  ......
}
```
1. `selector` is there to define which element (or array of elements) should be selected from the DOM for linting. The CSS selector used can be _anything_ (e.g. `#some-single-element`, or `.some-class` or `#some .thing:eq(3)[more="complicated"]`)
2. all other properties below `selector` are the actual **_checks_** that will be performed on whatever `$(selector)` returns. If `$(selector)` returns an array of elements, each check will be performed on each of the elements of that array.
<br>

Including some (or all)  _**checks**_ inside `selector` will not work:
```
selector: 'div.some-class[some-attr="some-value"]'
```
The above is not a "rule", it's merely a selector. The "linting" script will not be able to discern any "checks" out of the above selector. It can try to select the element from the DOM using the above `selector` but all "invalid" elements will be left out and the user will not be notified of anything.
<br>
So having said that,
<br>

**<h3>A.</h3>`is` and `isNot`:** 
Using both inside the same rule is redundant. I included both for the sake of the example on what's available. Being able to use them separately, however, is necessary: 
<br>
case 1 
```
{
  selector: '.some-selector',
  is: 'div'
}
```
if `.some-selector` is not a `<div/>`, the linter will throw an error (this is for elements whose tag must be `<x/>`)
<br>
case 2 
```
{
  selector: '.some-selector',
  isNot: 'p'
}
```
if `.some-selector` is a `<p/>`, the linter will throw an error (this is for elements whose tag can be anything but `<x/>`)
<br>
so the `is` , `isNot` _**checks**_ cannot be "part of" the `selector`

**<h3>B.</h3>`direct` and `indirect`:** 
It refers to `direct` and `indirect` children of the `selector`. I believe using `descendants` (meaning "indirect children") and `children` (meaning "direct children") is more ambiguous whereas `direct` and `indirect` is immediately understandable. However, I realised that that the best distinction actually could be:

```
"direct": ['.a'],
"contains": ['.b']
```

which means that the element being linted must have at least one direct child with the class `a` and it must also _contain_ (direct or indirect, it doesn't matter) at least one element with the class `b`. What do you think?

**<h3>C.</h3>`and` and `or`:** 
They are indeed unnecessary (i.e. too much) so I will remove them 🙂 

<h2>So we are left with the following possible examples:</h2>
 
```
{
  "selector": ".some-class-a",
  "is": "h3"
  "direct": [".a", ".b"],
  "contains": [".c", ".d"],
  "attr": ['e', 'f="g"']
}
```
which translates into:  _each element in the array returned by `$('.some-class-a'):`_
1. must be an `<h3/>`
2. must have at least one `.a` direct child
3. must have at least one `.b` direct child
4. must contain (anywhere) at least one `.c` child
5. must contain (anywhere) at least one `.d` child
6. must have these attributes: `[e]` and `[f="g"]`

and
```
{
  "selector": ".some-class-b",
  "isNot": "p"
  "not": {
    "direct": [".h", ".i"],
    "contains": [".j", ".k"],
    "attr": ['l', 'm="n"']
  }
}
```
which translates into:  _each element in the array returned by `$('.some-class-b'):`_
1. must not be a `<p/>`
2. must not have any `.h` direct children
3. must not have  any`.i` direct children
4. must not contain (anywhere) any `.j` children
5. must not contain (anywhere) any `.k` children
6. must not have these attributes: `[l]` and `[m="n"]

I agree 100% about splitting the configuration into multiple files. I'm assuming you mean allowing the user to do:

pdui-component-x.layoutrc

**Comment by xcambar** [comment]
This is much more readable!

```
{
  "selector": ".some-class-a",
  "is": "h3"
  "direct": [".a", ".b"],
  "contains": [".c", ".d"],
  "attr": ['e', 'f="g"']
},
{
  "selector": ".some-class-b",
  "not": {
    "is": "p"                       // <== Look here!
    "direct": [".h", ".i"],
    "contains": [".j", ".k"],
    "attr": ['l', 'm="n"']
  }
}
```

What do you think of this suggestion, to remove ~~isNot~~ in favor of `not.is` instead? It keeps the grammar lighter.

Take it or leave it, but whatever your choice regarding this last suggestion, I'd say that the grammar, as is, is ready to be tested against a codebase and actual use cases. Refinement will ensue "in the trenches". 🙂

**Comment by njoyard** [comment]
@Pixelik just a simple question : can you put selectors inside `is` or just element names? For example, would the following be valid:

```js
{
  "selector": ".some-class h1",
  "is": ".gray"
}
```

**Comment by Pixelik** [comment]
no, `is` is only for tag types (div, p, h1, a, etc...), it basically means `"isTag": ....`.

`attr` is for attributes (like classes etc..)

so `attr: [class="...."]`

**Comment by xcambar** [comment]
The constraints will have to be at least explained, certainly checked by the tool and ideally made obvious by naming convention.

But that's for later.

**Comment by Pixelik** [comment]
and : 
```
'attr': ['class="gray"']
``` 
is different than : 
```
'attr': ['class~="gray"']
``` 
(see [here](https://api.jquery.com/attribute-contains-word-selector/))

and both will be allowed and everything will be explained in the docs eventually :)

**Pull request merged**
